version: '3'
services:
  task_app:
    container_name: bot-app
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java_db
      SPRING_DATASOURCE_USERNAME: java
      SPRING_DATASOURCE_PASSWORD: root
    links:
      - postgres
  postgres:
    container_name: postgres-db
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: java_db
      POSTGRES_USER: java
      POSTGRES_PASSWORD: root